Feat/#12 question
Bamdoliro/marubase pull request #13
Opened 2023-05-18 15:13 UTC by hsem4717

## 🎫 관련 이슈

close #

<br>

## 📄 개요
> 

<br>

## 🔨 작업 내용
- update 작성했는데 테스트코드는 건드릴 엄두가 안나서 못했습니다.. 문제점 말해주시면 고치고 테스트 코드 작성해보겠습니다

<br>

## 🏁 확인 사항

- [ ] 테스트를 완료했나요?
- [ ] API 문서를 작성했나요?
- [ ] 코드 컨벤션을 준수했나요?

<br>

## 🙋🏻 덧붙일 말

2023-05-19 00:25 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/question/CreateQuestionUseCase.java
> +@Service
?

2023-05-19 00:25 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/question/UpdateQuestionUseCase.java
> +@Service
?

2023-05-19 00:25 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/question/UpdateQuestionUseCase.java
> +                () -> new IllegalArgumentException("Not Found Question")
custom exception 만들어주세요

2023-05-19 00:25 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/question/UpdateQuestionUseCase.java
> +        return question.updateData(request);
메서드 이름 그냥 update로 해도 괜찮을 것 같아요

2023-05-19 00:25 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/domain/question/domain/Question.java
> +    }
return을 왜 하는 건지?

2023-05-19 00:25 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/infrastructure/persistence/question/QuestionRepository.java
> +@Repository
필요 없습니다 다른 repository에서 안 넣으니까 여기서도 뺍시다for 통일성

2023-05-19 00:25 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/presentation/question/QuestionController.java
> +
?

2023-05-19 00:25 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/presentation/question/QuestionController.java
> +    }
?

2023-05-19 00:25 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/presentation/question/QuestionController.java
> +    }
response status NO_CONTENT gogo

2023-05-19 00:25 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/presentation/question/dto/request/UpdateQuestionRequest.java
> +@Getter
생성자 필요

2023-05-19 00:36 UTC, hsem4717 commented on src/main/java/com/bamdoliro/maru/presentation/question/QuestionController.java
> +
얘 의존성 주입 오류나서 주석 처리 해뒀습니다

Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'questionController' defined in file [/Users/devel/MARU/marubase/build/classes/java/main/com/bamdoliro/maru/presentation/question/QuestionController.class]: Unsatisfied dependency expressed through constructor parameter 1: No qualifying bean of type 'com.bamdoliro.maru.application.question.UpdateQuestionUseCase' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

2023-05-19 00:37 UTC, hsem4717 commented on src/main/java/com/bamdoliro/maru/presentation/question/QuestionController.java
> +
서버 실행이 안됩니다. 
환경 변수 보내주실수 있으실까요?

2023-05-21 14:19 UTC, gimhanul reviewed
controller단에서 create, update 전부 다 admin 권한만 보낼 수 있게 수정해주세여
전에 검색 키워드 줬던 걸로 기억합니당

2023-05-21 14:19 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/domain/question/domain/Question.java
> +    }
request 넣지 말고 title이랑 content ㅍㅏ라미터로 쓰는 걸로 바꿔주세여
결합도가 너무 높아진다 해야 하나

2023-05-21 14:19 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/domain/question/domain/Question.java
> +    private Long id;
```suggestion
    @Column(name = "question_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Id
    private Long id;
```
연관성 있는 어노테이션이 가까이 붙게 해주세여

2023-05-21 14:19 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/presentation/question/dto/request/UpdateQuestionRequest.java
> +}
validation annotation 추가해주세여

2023-05-21 14:19 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/presentation/question/dto/request/UpdateQuestionRequest.java
> +}
근데 어차피 CreateQuestionRequest랑 똑같으니까 저걸 QuestionRequest로 통일할까여

2023-05-21 14:19 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/presentation/question/dto/request/UpdateQuestionRequest.java
> +}
둘중하고싶은방식으로 ㄱㄱ
1. validation annotation 추가
2. QuestionRequest 통합

2023-05-21 14:19 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/question/UpdateQuestionUseCase.java
> +        );
메서드 추출하면 좋을듯 getQuestion 쯤으로

2023-05-21 14:20 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/presentation/question/QuestionController.java
> +
`ControlerTest.java` 여기였나 아무튼 이런 데에 `@MockBean` 에 업데이트 유즈케이스 추가하면 될 것 같은디

2023-05-23 09:07 UTC, hsem4717 commented on src/main/java/com/bamdoliro/maru/application/question/UpdateQuestionUseCase.java
> +        );
어디 넣어야해요...?

2023-05-23 10:05 UTC, hsem4717 commented on src/main/java/com/bamdoliro/maru/presentation/question/QuestionController.java
> +
혹시 왜 추가해야하는지 알려주실수 있으실까요?

2023-05-24 00:03 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/presentation/question/QuestionController.java
> +
QuestionController에서 UpdateQuestionUseCase를 의존하고 있는데, 
해당 controller를 테스트 할 때 이 테스트 객체를 만드려면 의존하고 있는 bean 들을 mocking해야 합니다
근데 mocking을 안 해놔서 테스트 객체를 만들 수 없어서 에러가 났던 겁니당

2023-05-24 00:07 UTC, gimhanul requested changes

2023-05-24 00:07 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/presentation/question/dto/request/UpdateQuestionRequest.java
> +@Valid
이건 validation annotation 먹여놓은 request를 사용할 때 `@RequestBody` annotation과 같이 사용하는 어노테이션입니다
잘 알아보고 다시 적용해주세여
CreateQuestionRequest 염탐 ㄱㄱ

2023-05-24 00:07 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/domain/question/exception/error/QuestionErrorProperty.java
> +    QUESTION_ID_NOT_FOUND(HttpStatus.NOT_FOUND, "해당 게시글을 찾을수 없습니다.");
```suggestion
    QUESTION_NOT_FOUND(HttpStatus.NOT_FOUND, "해당 질문을 찾을수 없습니다.");
```

2023-05-24 00:07 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/question/UpdateQuestionUseCase.java
> +        );
QuestionFacade 만들어주세여

2023-05-24 13:19 UTC, gimhanul requested changes

2023-05-24 13:19 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/question/QuestionFacade.java
> +}
bean으로 안 만들어주는데 동작이 되나요?
`@Component` 붙여주세여

2023-05-24 13:19 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/question/QuestionFacade.java
> +        );
Question**1**?

1은 왜 붙였죠?

2023-05-24 13:19 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/domain/question/exception/error/QuestionErrorProperty.java
> +    QUESTION_ID_NOT_FOUND(HttpStatus.NOT_FOUND, "해당 질문을 찾을수 없습니다.");
에러코드 QUESTION_ID~~어쩌고 에서 ID ㅈ빼ㅐ주세여
QUESTION_NOT_FOUND

2023-05-24 13:19 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/presentation/question/dto/request/UpdateQuestionRequest.java
>      private String content;
private String title;
이랑 @NotBlank어쩌고 사이에 엔터 한 번 ㄱㄱ

2023-05-24 14:21 UTC, gimhanul requested changes

2023-05-24 14:21 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/question/UpdateQuestionUseCase.java
> +@Validated
이건오ㅐ?

2023-05-24 14:21 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/question/UpdateQuestionUseCase.java
> +}
```suggestion
    @Transactional
    public void execute(Long id, UpdateQuestionRequest request) {
        Question question = questionFacade.getQuestion(id);
        question.update(request);
    }
}
```

2023-05-24 14:21 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/domain/question/domain/Question.java
> +    }
제발

2023-05-24 23:29 UTC, gimhanul requested changes
- [x] CI Failed 뜨는 거 고쳐주세여
- [x] QuestionId~Exception에서도 Id빼주세여
- [ ] usecase, controller 테스트해주세여

2023-05-25 12:34 UTC, hsem4717 commented
Api 문서 작성할때 참고할만한게 있을까요?
다른것 봐도 이해가 어렵습니다

2023-05-25 23:14 UTC, gimhanul commented
spring rest docs로 검색 ㄱㄱ

2023-05-27 11:10 UTC, leeseojune53 commented on src/main/java/com/bamdoliro/maru/application/question/CreateQuestionUseCase.java
> +    @Transactional
save method만 사용하는데 Transactional을 사용한 이유가 있을까요?

2023-05-29 07:45 UTC, hsem4717 commented
?? 뭐야

2023-05-29 07:45 UTC, hsem4717 commented
헐 죄송해요 잘못 요청했어요

2023-05-29 07:47 UTC, hsem4717 commented
한울선배 테스트 코드 짜봤는데 없으면 에러 발생하는거 오류가 Null값이래요 혹시 왜그런지 알수 있을까요?

2023-05-29 07:55 UTC, hsem4717 commented on src/main/java/com/bamdoliro/maru/application/question/CreateQuestionUseCase.java
> +    @Transactional
Transaction은 저장후에 일관성 유지를 위해 사용한다고 알고 있었습니다 하지만 알아보니 단일작업일 경우에는 사용하지 않아도 되는것 같습니다 알려주셔서 감사합니다

2023-05-29 11:31 UTC, gimhanul commented
> 한울선배 테스트 코드 짜봤는데 없으면 에러 발생하는거 오류가 Null값이래요 혹시 왜그런지 알수 있을까요?

내가우째알아…
디버깅 ㄱㄱ

2023-05-29 15:37 UTC, leeseojune53 approved these changes
LGTM @hsem4717  👍

2023-05-30 12:34 UTC, gimhanul requested changes

2023-05-30 12:34 UTC, gimhanul commented on src/test/java/com/bamdoliro/maru/presentation/question/QuestionControllerTest.java
> +        mockMvc.perform(MockMvcRequestBuilders.put("/question/{id}", id)
RestDocumentationRequestBuilders 로 static import해서 쓰면 댐니다

위쪽에 `post()` 쓴 거 참고해주세여

2023-05-30 12:34 UTC, gimhanul commented on src/test/java/com/bamdoliro/maru/presentation/question/QuestionControllerTest.java
> +                        )
PathVariable로 넣는 id도 문서화에 추가해주세여

2023-05-30 12:34 UTC, gimhanul commented on src/test/java/com/bamdoliro/maru/presentation/question/QuestionControllerTest.java
> +
얘도 rest docs document() 한 번 불러줘야 문서화 됩니다

2023-05-30 12:35 UTC, gimhanul commented
conflict 고치면 파일 합쳐져서 복잡해지니께 머지하기 전에 conflict 고칩시더

2023-05-31 13:25 UTC, hsem4717 commented
밑에 저 사고친거에요? 아직 아니겠죠..?

2023-05-31 13:41 UTC, gimhanul commented
ㄴㄴ 저거 그냥 내가 머지해서 그럼

2023-06-01 23:40 UTC, hsem4717 commented
선배 이제 뭐해야 해요?

2023-06-02 00:48 UTC, gimhanul requested changes
이게 마지막 리뷰가 댈듯함니다 파이팅

2023-06-02 00:48 UTC, gimhanul commented on src/docs/asciidoc/question.adoc
> +include::{snippets}/question-controller-test/자주묻는질문을_수정한다/request-headers.adoc[]
```suggestion
===== Request Header
include::{snippets}/question-controller-test/자주묻는질문을_수정한다/request-headers.adoc[]
```

2023-06-02 00:48 UTC, gimhanul commented on src/docs/asciidoc/question.adoc
> +include::{snippets}/question-controller-test/자주묻는질문을_수정한다/request-headers.adoc[]
밑에 있는 거 다 이렇게 고쳐주세용

2023-06-02 00:48 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/question/QuestionFacade.java
> +public class QuestionFacade {
연관있는 걸 가장 가까이에

2023-06-02 00:48 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/presentation/question/QuestionController.java
> +    @ResponseStatus(HttpStatus.CREATED)
```suggestion
    @ResponseStatus(HttpStatus.CREATED)
    @PreAuthorize("hasRole('ROLE_ADMIN')")
    @PostMapping
```

2023-06-02 00:48 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/presentation/question/QuestionController.java
> +    @ResponseStatus(HttpStatus.CREATED)
순서 이렇게 통일합ㄴ시다

2023-06-02 00:48 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/presentation/question/QuestionController.java
> +    @ResponseStatus(HttpStatus.CREATED)
(밑에것도하라는뜻)

2023-06-02 00:48 UTC, gimhanul commented on src/test/java/com/bamdoliro/maru/application/question/UpdateQuestionUseCaseTest.java
> +    }
```suggestion
        //when
        updateQuestionUseCase.execute(question.getId(), request);
        
        // then
        verify(questionFacade, times(1)).getQuestion(question.getId());
        assertEquals(request.getTitle(), question.getTitle());
        assertEquals(request.getContent(), question.getContent());
    }
```

2023-06-02 00:48 UTC, gimhanul commented on src/test/java/com/bamdoliro/maru/presentation/question/QuestionControllerTest.java
> +                        .content(objectMapper.writeValueAsString(request)))
```suggestion
                        .content(toJson(request)))
```

상위 상위 클래스에 toJson 메서드가 있어서 그거 쓰시면 댐니다

2023-06-02 03:24 UTC, hsem4717 commented on src/main/java/com/bamdoliro/maru/application/question/QuestionFacade.java
> +public class QuestionFacade {
선배 이거 바꾸긴 했는데 연관성 우선순위는 어떻게 정해지는거에요?

2023-06-03 03:03 UTC, leeseojune53 commented on src/main/java/com/bamdoliro/maru/application/question/QuestionFacade.java
> +public class QuestionFacade {
아마도 Component, Service, Repository와 같은 Spring Bean을 등록하는걸 Type 제일 가까이 선언하고(critical), 비교적 중요도가 낮은(compile time에서 명확하게 확인할 수 있는) RequiredArgsConstructor를 Type 멀리 선언하는걸 이야기하는 듯 합니다 :)

2023-06-03 03:04 UTC, leeseojune53 commented on src/main/java/com/bamdoliro/maru/application/question/QuestionFacade.java
> +public class QuestionFacade {
또, 위와 같은 상황일때는 그냥 물어보는 것 보다는
'나는 이케 생각하는데 이게 맞나요?' 라고 물어보는게 더 많은 성장이 있을거예요 😃

2023-06-03 05:21 UTC, hsem4717 commented on src/main/java/com/bamdoliro/maru/application/question/QuestionFacade.java
> +public class QuestionFacade {
앗 넵 답변해주셔서 감사합니다

2023-06-06 23:02 UTC, gimhanul approved these changes
수하습
(수고하셨습니다라는뜻)

2023-06-06 23:09 UTC, merged