Feat/#83
Bamdoliro/marubase pull request #84
Opened 2024-06-01 10:13 UTC by jyj1289

## 🎫 관련 이슈
[//]: # (다음 키워드를 사용하면 해당 PR을 머지할 때 자동으로 이슈를 닫을 수 있습니다.)
[//]: # (keyword: close|closes|closed|resolve|resolves|resolved|fix|fixes|fixed)
[//]: # (예시: close #1)

close #83 

<br>

## 📄 개요
[//]: # (작업 내용을 간단히 요약해서 적습니다.)
[//]: # (예시: 유저 회원가입 기능을 만들었습니다.)

> 유저 비밀번호 변경 기능을 만들었습니다.

<br>

## 🔨 작업 내용
[//]: # (작업 내용을 자세하게 적습니다.)
[//]: # (붙임표 "-" 을 사용해서 목록을 만듭니다.)
[//]: # (예시: 유저 회원가입 API를 만들었습니다.)

- 유저 비밀번호 변경 API를 만들었습니다.
- 유저 클래스에 비밀번호 변경 메서드를 추가했습니다.
- 유저 생성 유즈케이스의 내용을 변경하였습니다.

<br>

## 🏁 확인 사항
[//]: # (PR을 보내기 전 다음 사항을 확인해주세요.)
[//]: # (해당 사항을 모두 이행해야 머지할 수 있습니다.)
[//]: # (- [x] 를 사용해서 완료로 표시할 수 있습니다.)

- [x] 테스트를 완료했나요?
- [x] API 문서를 작성했나요?
- [x] 코드 컨벤션을 준수했나요?
- [x] 불필요한 로그, 주석, import 등을 삭제했나요?

<br>

## 🙋🏻 덧붙일 말
[//]: # (다음 사항이 있다면 적어주세요.)
[//]: # (PR에 대한 추가 설명)
[//]: # (중점적으로 리뷰받고 싶은 부분)
[//]: # (기타 등등)

2024-06-03 02:14 UTC, gimhanul requested changes
열심히 테스트하는 모습 좋습니다!

2024-06-03 02:14 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/user/SignUpUserUseCase.java
> +        verificationRepository.updateVerification(
p2) false 상태로 만들어주는 것보다 삭제하는 게 낫지 않을까용?

2024-06-03 02:14 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/user/SendVerificationUseCase.java
> +                "[부산소프트웨어마이스터고] 인증번호는 [%s]입니다.",
P1) 개인적인 생각이긴 한데, 요런 건 **인증번호를 받는 목적을 정확하게 명시**해줘야 한다고 생각해요
만약 고의로 다른 사람의 전화번호를 입력한다면 생각지 못한 일이 생길수도 있으니까?요

또한, "회원가입"을 위한 인증번호 저장소와 "비밀번호 변경"을 위한 인증번호 저장소를 같은 곳을 사용하면 안 돼요
트랜잭션 관리가 된다면 문제 없을 거 같긴 하지만, 기억상 redis는 `@Transactional` 트랙잭션이 안 걸리는 걸로 알고 있거든요

그래서 **redis 트랜잭션을 관리하거나, 인증번호 별 저장소를 분리하는 식**으로 관리가 되어야 할 거 같습니다

2024-06-03 02:14 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/user/SignUpUserUseCase.java
> +        verificationRepository.updateVerification(
추가로 Verificaiton 도메인 보면 유효 시간 걸려있는 거 참고해주세요!

2024-06-03 02:14 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/user/UpdatePasswordUseCase.java
> +        if (!userRepository.existsByPhoneNumber(request.getPhoneNumber())) {
P2) 굳이 이 메서드를 부를 필요가 없을 거 같아요
쿼리문이 오히려 두 번 나가서 손해일 거 같습니다
`userFacade.getUser()` 메서드가 findById 후에 유저가 없다면 orElseThrow로 아마 exception 던져주고 있을 거거든요

2024-06-03 02:14 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/user/UpdatePasswordUseCase.java
> +        verificationRepository.updateVerification(
p2) false 상태로 만들어주는 것보다 삭제하는 게 낫지 않을까용?

2024-06-03 02:14 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/presentation/user/UserController.java
> +    @PutMapping("/password-update")
P1) Http method중 put과 patch의 차이점을 알아보고 잘 구분해서 쓰면 더 적절하게 설계할 수 있을 거 같아요
그리고, password-update처럼 url에 동사를 넣지 않는 게 나을 거 같아요 어차피 put이나 patch가 update한다는 사실을 충분히 설명하고 있으니까용

2024-06-03 02:15 UTC, gimhanul commented on src/main/java/com/bamdoliro/maru/application/user/UpdatePasswordUseCase.java
> +        if (!userRepository.existsByPhoneNumber(request.getPhoneNumber())) {
facade 한 번 뜯어보고 결정해주세요! 아닐 수도 있어서 ㅎㅎ

2024-06-11 13:44 UTC, jyj1289 commented
저도 이 코드가 맞는지 모르겠습니다...🥲

2024-06-11 17:07 UTC, merged